server:
  port: 16001
spring:
  application:
    name: coderiver-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coderiver_base?characterEncoding=utf-8
    username: username
    password: password
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
